/**
 * @description       : This is just for initial deployment so MetaCI does not 
 * throw an error
 * @author            : Bryan Anderson
 * @group             : 
 * @last modified on  : 08-31-2020
 * @last modified by  : Bryan Anderson
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   07-15-2020   Bryan Anderson   Initial Version
**/
public with sharing class MyClass
{
    public static void myMethod()
    {
        System.debug('Hello From Harting!');
    }
}
